version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: geosurvey_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: geosurvey_pbb
      MYSQL_USER: user_pbb
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Mount file init.sql agar dijalankan otomatis saat db pertama kali dibuat
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot_password_here"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geosurvey_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password_here
      - DB_NAME=geosurvey_pbb
      - JWT_SECRET=supersecretjwtkey_geosurvey
      - JWT_EXPIRES_IN=7d
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
