name: geosurvey_pbb
description: Aplikasi survei lapangan untuk pendataan Pajak Bumi dan Bangunan

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client untuk panggil API
  dio: ^5.4.3+1

  # Penyimpanan lokal (JWT token, user session)
  shared_preferences: ^2.2.3

  # Routing navigasi
  go_router: ^13.2.0

  # Icon pack tambahan
  cupertino_icons: ^1.0.6

  # Fonts dari Google
  google_fonts: ^6.2.1

  # Phase 3: Scanner QR Code & Barcode
  # Bekerja di Flutter Web menggunakan kamera browser
  mobile_scanner: ^7.2.0

  # Phase 4: Kamera & GPS & SQLite
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  camera: ^0.12.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  sqflite_common_ffi_web: ^1.1.2

flutter:
  uses-material-design: true